package hard

// DO NOT EDIT - generated by aliasgen tool (github.com/rhuairahrighairidh/aliasgen)

import (
	"github.com/kava-labs/kava/x/hard/keeper"
	"github.com/kava-labs/kava/x/hard/types"
)

const (
	AttributeKeyBlockHeight            = types.AttributeKeyBlockHeight
	AttributeKeyDeposit                = types.AttributeKeyDeposit
	AttributeKeyDepositDenom           = types.AttributeKeyDepositDenom
	AttributeKeyDepositor              = types.AttributeKeyDepositor
	AttributeKeyRewardsDistribution    = types.AttributeKeyRewardsDistribution
	AttributeValueCategory             = types.AttributeValueCategory
	DefaultParamspace                  = types.DefaultParamspace
	DelegatorAccount                   = types.DelegatorAccount
	EventTypeDeleteHardDeposit         = types.EventTypeDeleteHardDeposit
	EventTypeHardDelegatorDistribution = types.EventTypeHardDelegatorDistribution
	EventTypeHardDeposit               = types.EventTypeHardDeposit
	EventTypeHardLPDistribution        = types.EventTypeHardLPDistribution
	EventTypeHardWithdrawal            = types.EventTypeHardWithdrawal
	LPAccount                          = types.LPAccount
	LiquidatorAccount                  = types.LiquidatorAccount
	Large                              = types.Large
	Medium                             = types.Medium
	ModuleAccountName                  = types.ModuleAccountName
	ModuleName                         = types.ModuleName
	QuerierRoute                       = types.QuerierRoute
	QueryGetDeposits                   = types.QueryGetDeposits
	QueryGetModuleAccounts             = types.QueryGetModuleAccounts
	QueryGetParams                     = types.QueryGetParams
	RouterKey                          = types.RouterKey
	Small                              = types.Small
	StoreKey                           = types.StoreKey
)

var (
	// function aliases
	NewKeeper                     = keeper.NewKeeper
	NewQuerier                    = keeper.NewQuerier
	CalculateUtilizationRatio     = keeper.CalculateUtilizationRatio
	CalculateBorrowRate           = keeper.CalculateBorrowRate
	CalculateBorrowInterestFactor = keeper.CalculateBorrowInterestFactor
	CalculateSupplyInterestFactor = keeper.CalculateSupplyInterestFactor
	APYToSPY                      = keeper.APYToSPY
	DefaultGenesisState           = types.DefaultGenesisState
	DefaultParams                 = types.DefaultParams
	DepositTypeIteratorKey        = types.DepositTypeIteratorKey
	GetTotalVestingPeriodLength   = types.GetTotalVestingPeriodLength
	NewBorrowLimit                = types.NewBorrowLimit
	NewInterestRateModel          = types.NewInterestRateModel
	NewDeposit                    = types.NewDeposit
	NewGenesisState               = types.NewGenesisState
	NewMsgDeposit                 = types.NewMsgDeposit
	NewMsgWithdraw                = types.NewMsgWithdraw
	NewMultiHARDHooks             = types.NewMultiHARDHooks
	NewMultiplier                 = types.NewMultiplier
	NewParams                     = types.NewParams
	NewPeriod                     = types.NewPeriod
	NewMoneyMarket                = types.NewMoneyMarket
	NewQueryAccountParams         = types.NewQueryAccountParams
	ParamKeyTable                 = types.ParamKeyTable
	RegisterCodec                 = types.RegisterCodec

	// variable aliases
	BorrowsKeyPrefix                 = types.BorrowsKeyPrefix
	DefaultActive                    = types.DefaultActive
	DefaultPreviousBlockTime         = types.DefaultPreviousBlockTime
	DepositsKeyPrefix                = types.DepositsKeyPrefix
	ErrAccountNotFound               = types.ErrAccountNotFound
	ErrDepositNotFound               = types.ErrDepositNotFound
	ErrGovScheduleNotFound           = types.ErrGovScheduleNotFound
	ErrInsufficientModAccountBalance = types.ErrInsufficientModAccountBalance
	ErrInvaliWithdrawAmount          = types.ErrInvalidWithdrawAmount
	ErrInvalidAccountType            = types.ErrInvalidAccountType
	ErrInvalidDepositDenom           = types.ErrInvalidDepositDenom
	ErrInvalidMultiplier             = types.ErrInvalidMultiplier
	ErrLPScheduleNotFound            = types.ErrLPScheduleNotFound
	GovDenom                         = types.GovDenom
	KeyActive                        = types.KeyActive
	ModuleCdc                        = types.ModuleCdc
	PreviousBlockTimeKey             = types.PreviousBlockTimeKey
)

type (
	Keeper             = keeper.Keeper
	AccountKeeper      = types.AccountKeeper
	Borrow             = types.Borrow
	MoneyMarket        = types.MoneyMarket
	MoneyMarkets       = types.MoneyMarkets
	Deposit            = types.Deposit
	GenesisState       = types.GenesisState
	MsgDeposit         = types.MsgDeposit
	MsgWithdraw        = types.MsgWithdraw
	Multiplier         = types.Multiplier
	MultiplierName     = types.MultiplierName
	Multipliers        = types.Multipliers
	Params             = types.Params
	QueryAccountParams = types.QueryAccountParams
	StakingKeeper      = types.StakingKeeper
	SupplyKeeper       = types.SupplyKeeper
)
