// Code generated by mockery 2.7.4. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	math "cosmossdk.io/math"

	types "github.com/cosmos/cosmos-sdk/types"
)

// SwapHooks is an autogenerated mock type for the SwapHooks type
type SwapHooks struct {
	mock.Mock
}

// AfterPoolDepositCreated provides a mock function with given fields: ctx, poolID, depositor, sharedOwned
func (_m *SwapHooks) AfterPoolDepositCreated(ctx types.Context, poolID string, depositor types.AccAddress, sharedOwned math.Int) {
	_m.Called(ctx, poolID, depositor, sharedOwned)
}

// BeforePoolDepositModified provides a mock function with given fields: ctx, poolID, depositor, sharedOwned
func (_m *SwapHooks) BeforePoolDepositModified(ctx types.Context, poolID string, depositor types.AccAddress, sharedOwned math.Int) {
	_m.Called(ctx, poolID, depositor, sharedOwned)
}
