run:
  timeout: 20m
  modules-download-mode: readonly
  issues-exit-code: 0
  allow-parallel-runners: true


linters-settings:
  errcheck:
    check-blank: true
    check-type-assertions: false
  revive:
    severity: error
    rules:
      - name: exported
        arguments: ["checkPrivateReceivers", "disableStutteringCheck", "sayRepetitiveInsteadOfStutters"]
  errorlint:
    check-generated: false
    default-signifies-exhaustive: false
  exhaustive:
    default-signifies-exhaustive: false
  gci:
    sections:
      - standard
      - default
  goconst:
    min-len: 3
    min-occurrences: 3
  godox:
    keywords:
      - BUG
      - FIXME
      - HACK
  lll:
    line-length: 140
  nolintlint:
    allow-leading-space: false
    require-explanation: true
    require-specific: true
  unparam:
    check-exported: true
  misspell:
    locale: US
    ignore-words: expect
  prealloc:
    simple: true
    range-loops: true
    for-loops: false

linters:
  disable-all: true
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - decorder
    - dogsled
    - dupl
    - dupword
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - exportloopref
    - gci
    - ginkgolinter
    - gocheckcompilerdirectives
    - gochecknoglobals
    - gochecknoinits
    - goconst
    - gocritic
    - godox
    - gofmt
    - gofumpt
    - goheader
    - goimports
    - mnd
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - grouper
    - importas
    - ineffassign
    - interfacebloat
    - lll
    - loggercheck
    - makezero
    - mirror
    - misspell
    - musttag
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - nonamedreturns
    - nosprintfhostport
    - prealloc
    - predeclared
    - reassign
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - stylecheck
    - tagalign
    - testpackage
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - wastedassign
    - whitespace

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - cyclop
        - dupl
        - errcheck
        - gochecknoglobals
        - gochecknoinits
        - goconst
        - mnd
        - noctx
    - linters:
        - gosec
      text: "math/rand"
      path: _test\.go
    - linters:
        - gosec
      text: "TLS InsecureSkipVerify set true"
      path: _test\.go
    - linters:
        - gosec
      text: "G108: Profiling endpoint is automatically exposed on /debug/pprof"
      path: _test\.go