FROM golang:1.20-alpine AS build-env

# Set up dependencies
# bash, jq, curl for debugging
# git, make for installation
# libc-dev, gcc, linux-headers, eudev-dev are used for cgo and ledger installation
RUN apk add bash git make libc-dev gcc linux-headers eudev-dev jq curl

# Set working directory for the build
WORKDIR /root/kava
# default home directory is /root

# TODO: it's necessary only for local development, remove before merging
COPY ./docker-deps/ethermint   /Users/yevheniishcherbina/go/src/github.com/Kava-Labs/ethermint
COPY ./docker-deps/go-ethereum /Users/yevheniishcherbina/go/src/github.com/ethereum/go-ethereum

#ENV LEDGER_ENABLED False

# Add source files and install kava
COPY . .
RUN make install

FROM alpine:3.15

RUN apk add bash jq curl
COPY --from=build-env /go/bin/kava /bin/kava

CMD ["kava"]
