name: Setup Go
description: Install Go
runs:
  using: composite
  steps:
    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ env.GO_VERSION }}
        go-version-file: go.mod
        cache-dependency-path: go.sum
        cache: true
    - name: Set Cache Path
      id: paths
      run: |
        echo "GOBUILD_PATH=$(go env GOCACHE)" >> "$GITHUB_OUTPUT"
        echo "GOMOD_PATH=$(go env GOMODCACHE)" >> "$GITHUB_OUTPUT"
      shell: bash
    - name: Go Build Cache
      uses: actions/cache@v4
      with:
        path: ${{ steps.paths.outputs.GOBUILD_PATH }}
        key: ${{ runner.os }}-go-build-${{ hashFiles('**/go.sum') }}
    - name: Go Mod Cache
      uses: actions/cache@v4
      with:
        path: ${{ steps.paths.outputs.GOMOD_PATH }}
        key: ${{ runner.os }}-go-build-${{ hashFiles('**/go.mod') }}
    - name: Run go mod download
      run: |
        go mod download
      shell: bash