// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: kava/liquidstaking/v1beta1/store.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params defines the parameters for the liquidstaking module.
type Params struct {
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0b706021645b5c6, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

// DelegationHolder defines a DelegationHolder
type DelegationHolder struct {
	// module account address
	ModuleAccount github_com_cosmos_cosmos_sdk_types.AccAddress `protobuf:"bytes,1,opt,name=module_account,json=moduleAccount,proto3,casttype=github.com/cosmos/cosmos-sdk/types.AccAddress" json:"module_account,omitempty"`
	// validator's address
	Validator github_com_cosmos_cosmos_sdk_types.ValAddress `protobuf:"bytes,2,opt,name=validator,proto3,casttype=github.com/cosmos/cosmos-sdk/types.ValAddress" json:"validator,omitempty"`
	// kava delegation share amount
	Delegations types.Coin `protobuf:"bytes,3,opt,name=delegations,proto3" json:"delegations"`
}

func (m *DelegationHolder) Reset()         { *m = DelegationHolder{} }
func (m *DelegationHolder) String() string { return proto.CompactTextString(m) }
func (*DelegationHolder) ProtoMessage()    {}
func (*DelegationHolder) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0b706021645b5c6, []int{1}
}
func (m *DelegationHolder) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DelegationHolder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DelegationHolder.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *DelegationHolder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelegationHolder.Merge(m, src)
}
func (m *DelegationHolder) XXX_Size() int {
	return m.Size()
}
func (m *DelegationHolder) XXX_DiscardUnknown() {
	xxx_messageInfo_DelegationHolder.DiscardUnknown(m)
}

var xxx_messageInfo_DelegationHolder proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Params)(nil), "kava.liquidstaking.v1beta1.Params")
	proto.RegisterType((*DelegationHolder)(nil), "kava.liquidstaking.v1beta1.DelegationHolder")
}

func init() {
	proto.RegisterFile("kava/liquidstaking/v1beta1/store.proto", fileDescriptor_d0b706021645b5c6)
}

var fileDescriptor_d0b706021645b5c6 = []byte{
	// 351 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0x3f, 0x4e, 0xf3, 0x30,
	0x14, 0x4f, 0xfa, 0x7d, 0xaa, 0x68, 0x0a, 0x08, 0x05, 0x86, 0xb6, 0x83, 0x5b, 0x75, 0x40, 0x5d,
	0x12, 0xab, 0x70, 0x82, 0x04, 0x86, 0x2e, 0x48, 0xa8, 0x03, 0x03, 0x4b, 0xe5, 0xc4, 0x26, 0x58,
	0x4d, 0xf2, 0x4a, 0xec, 0x54, 0xf4, 0x16, 0x9c, 0x84, 0x89, 0x43, 0x74, 0xac, 0x98, 0x98, 0x2a,
	0x68, 0x6f, 0xc1, 0x84, 0x12, 0x9b, 0x52, 0x58, 0x60, 0xca, 0x8b, 0x7f, 0xff, 0x9e, 0xdf, 0xb3,
	0x75, 0x3c, 0x26, 0x53, 0x82, 0x63, 0x7e, 0x97, 0x73, 0x2a, 0x24, 0x19, 0xf3, 0x34, 0xc2, 0xd3,
	0x7e, 0xc0, 0x24, 0xe9, 0x63, 0x21, 0x21, 0x63, 0xee, 0x24, 0x03, 0x09, 0x76, 0xab, 0xe0, 0xb9,
	0xdf, 0x78, 0xae, 0xe6, 0xb5, 0x8e, 0x22, 0x88, 0xa0, 0xa4, 0xe1, 0xa2, 0x52, 0x8a, 0x16, 0x0a,
	0x41, 0x24, 0x20, 0x70, 0x40, 0x04, 0xdb, 0x58, 0x86, 0xc0, 0x53, 0x8d, 0x37, 0x15, 0x3e, 0x52,
	0x42, 0xf5, 0xa3, 0xa0, 0xee, 0x8e, 0x55, 0xbd, 0x24, 0x19, 0x49, 0x44, 0xf7, 0xb1, 0x62, 0x1d,
	0x9c, 0xb3, 0x98, 0x45, 0x44, 0x72, 0x48, 0x07, 0x10, 0x53, 0x96, 0xd9, 0x60, 0xed, 0x27, 0x40,
	0xf3, 0x98, 0x8d, 0x48, 0x18, 0x42, 0x9e, 0xca, 0x86, 0xd9, 0x31, 0x7b, 0xbb, 0xfe, 0xe0, 0x7d,
	0xd9, 0x76, 0x22, 0x2e, 0x6f, 0xf3, 0xc0, 0x0d, 0x21, 0xd1, 0x9e, 0xfa, 0xe3, 0x08, 0x3a, 0xc6,
	0x72, 0x36, 0x61, 0xc2, 0xf5, 0xc2, 0xd0, 0xa3, 0x34, 0x63, 0x42, 0x3c, 0x3f, 0x39, 0x87, 0x3a,
	0x59, 0x9f, 0xf8, 0x33, 0xc9, 0xc4, 0x70, 0x4f, 0xf9, 0x7b, 0xca, 0xde, 0xbe, 0xb1, 0x6a, 0x53,
	0x12, 0x73, 0x4a, 0x24, 0x64, 0x8d, 0x4a, 0xc7, 0xec, 0xd5, 0xfe, 0x9c, 0x75, 0x45, 0xe2, 0x5f,
	0xb2, 0xbe, 0xac, 0x6d, 0xcf, 0xaa, 0xd3, 0xcd, 0x65, 0x45, 0xe3, 0x5f, 0xc7, 0xec, 0xd5, 0x4f,
	0x9a, 0xae, 0x56, 0x15, 0x83, 0xfc, 0x9c, 0xb9, 0x7b, 0x06, 0x3c, 0xf5, 0xff, 0xcf, 0x97, 0x6d,
	0x63, 0xb8, 0xad, 0xf1, 0x2f, 0xe6, 0x6f, 0xc8, 0x98, 0xaf, 0x90, 0xb9, 0x58, 0x21, 0xf3, 0x75,
	0x85, 0xcc, 0x87, 0x35, 0x32, 0x16, 0x6b, 0x64, 0xbc, 0xac, 0x91, 0x71, 0x8d, 0xb7, 0x3a, 0x2e,
	0x16, 0xea, 0xc4, 0x24, 0x10, 0x65, 0x85, 0xef, 0x7f, 0x3c, 0x82, 0xb2, 0xfd, 0xa0, 0x5a, 0x2e,
	0xe4, 0xf4, 0x23, 0x00, 0x00, 0xff, 0xff, 0xfa, 0x46, 0x85, 0x05, 0x27, 0x02, 0x00, 0x00,
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *DelegationHolder) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DelegationHolder) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DelegationHolder) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Delegations.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintStore(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if len(m.Validator) > 0 {
		i -= len(m.Validator)
		copy(dAtA[i:], m.Validator)
		i = encodeVarintStore(dAtA, i, uint64(len(m.Validator)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.ModuleAccount) > 0 {
		i -= len(m.ModuleAccount)
		copy(dAtA[i:], m.ModuleAccount)
		i = encodeVarintStore(dAtA, i, uint64(len(m.ModuleAccount)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintStore(dAtA []byte, offset int, v uint64) int {
	offset -= sovStore(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *DelegationHolder) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ModuleAccount)
	if l > 0 {
		n += 1 + l + sovStore(uint64(l))
	}
	l = len(m.Validator)
	if l > 0 {
		n += 1 + l + sovStore(uint64(l))
	}
	l = m.Delegations.Size()
	n += 1 + l + sovStore(uint64(l))
	return n
}

func sovStore(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozStore(x uint64) (n int) {
	return sovStore(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowStore
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipStore(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthStore
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *DelegationHolder) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowStore
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DelegationHolder: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DelegationHolder: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ModuleAccount", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStore
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthStore
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthStore
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ModuleAccount = append(m.ModuleAccount[:0], dAtA[iNdEx:postIndex]...)
			if m.ModuleAccount == nil {
				m.ModuleAccount = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Validator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStore
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthStore
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthStore
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Validator = github_com_cosmos_cosmos_sdk_types.ValAddress(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Delegations", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStore
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthStore
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthStore
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Delegations.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipStore(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthStore
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipStore(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowStore
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowStore
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowStore
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthStore
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupStore
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthStore
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthStore        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowStore          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupStore = fmt.Errorf("proto: unexpected end of group")
)
