name: Continuous Deployment (Protonet)
# run after every successful CI job of new commits to the master branch
on:
  workflow_run:
    workflows: [Continuous Integration (Kava Master)]
    types:
      - completed

jobs:
  changed_files:
    runs-on: ubuntu-latest
    # define output for first job forwarding output of changedProtonetConfig job
    outputs:
      changedProtonetConfig: ${{ steps.changed-protonet-config.outputs.any_changed }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # OR "2" -> To retrieve the preceding commit.
      - name: Get all changed protonet files
        id: hanged-protonet-config
        uses: tj-actions/changed-files@v42
        with:
          # Avoid using single or double quotes for multiline patterns
          files: |
            ci/env/kava-protonet/**

  # in order:
  # enter standby (prevents autoscaling group from killing node during deploy)
  # stop doctor and kava
  # download updated binary and genesis
  # reset application database state
  # restart all once all have been reset
  # start kava and doctor
  # enter inService
  reset-chain-to-zero-state:
    # only start cd pipeline if last ci run was successful
    if: ${{ github.event.workflow_run.conclusion == 'success' && needs.changed_files.outputs.changedProtonetConfig == 'true' }}
    uses: ./.github/workflows/cd-reset-protonet.yml
    with:
      aws-region: us-east-1
      chain-tag-name: ChainId
      chain-id: proto_2221-17000
      auto_scaling_group_names: kava-protonet-iavl-v1-validator-api-node,kava-protonet-iavl-v1-rpc-api-node
      ssm-document-name: kava-protonet-iavl-v1-instance-update
      playbook-name: reset-chain.yml
      playbook-infrastructure-branch: master
    secrets: inherit


  restart-chain:
      uses: ./.github/workflows/cd-restart-protonet.yml
      with:
        aws-region: us-east-1
        chain-tag-name: ChainId
        chain-id: proto_2221-17000
        auto_scaling_group_names: kava-protonet-iavl-v1-validator-api-node,kava-protonet-iavl-v1-rpc-api-node
        ssm-document-name: kava-protonet-iavl-v1-instance-update
        playbook-name: restart-chain.yml
        playbook-infrastructure-branch: master
      secrets: inherit
      needs: [ reset-chain-to-zero-state ]

  # setup test and development accounts and balances, deploy contracts by calling the chain's api
  seed-chain-state:
    uses: ./.github/workflows/cd-seed-chain.yml
    with:
      chain-api-url: https://rpc.app.protonet.us-east.production.kava.io:443
      chain-id: proto_2221-17000
      seed-script-filename: seed-protonet.sh
      erc20-deployer-network-name: protonet
      genesis_validator_addresses: "kavavaloper1jaw3g097lq9jdrnscchspr2233yhpsxdlq7ula"
      kava_version_filepath:  ./ci/env/kava-protonet/KAVA.VERSION
    secrets: inherit
    needs: [restart-chain]

  post-pipeline-metrics:
    uses: ./.github/workflows/metric-pipeline.yml
    if: always() # always run so we metric failures and successes
    with:
      aws-region: us-east-1
      metric-name: kava.deploys.protonet.proto
      namespace: Kava/ContinuousDeployment
    secrets: inherit
    needs: [seed-chain-state]