name: Continuous Deployment (Protonet)

## run after every successful CI job of new commits to the master branch, or on manual dispatch
on:
  workflow_run:
    workflows: [Continuous Integration (Kava Master)]
    types:
      - completed
  workflow_dispatch:

jobs:
  reset-and-restart-chain:
    # only start cd pipeline if last ci run was successful (or it this is being manually dispatched)
    if: |
      github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success')
    uses: ./.github/workflows/cd-reset-network.yml
    with:
      aws-region: us-east-1
      chain-id: proto_2221-17000
      ssm-document-name: kava-protonet-api-instance-update
      playbook-infrastructure-branch: master
    secrets: inherit

  # setup test and development accounts and balances, deploy contracts by calling the chain's api
  seed-chain-state:
    uses: ./.github/workflows/cd-seed-chain.yml
    with:
      chain-api-url: https://rpc.app.protonet.us-east.production.kava.io:443
      chain-id: proto_2221-17000
      seed-script-filename: seed-protonet.sh
      erc20-deployer-network-name: protonet
      genesis_validator_addresses: "kavavaloper14w4avgdvqrlpww6l5dhgj4egfn6ln7gmtp7r2m"
      kava_version_filepath: ./ci/env/kava-protonet/KAVA.VERSION
    secrets: inherit
    needs: [reset-and-restart-chain]

  post-pipeline-metrics:
    uses: ./.github/workflows/metric-pipeline.yml
    if: always() # always run so we metric failures and successes
    with:
      aws-region: us-east-1
      metric-name: kava.deploys.testnet.proto
      namespace: Kava/ContinuousDeployment
    secrets: inherit
    needs: [seed-chain-state]
