name: Lint Checks
on:
  workflow_call:
# run per commit ci checks against this commit
jobs:
  proto-lint:
    uses: ./.github/workflows/proto.yml
  golangci-lint:
    runs-on: ubuntu-latest
    permissions:
      checks: write # allow write access to checks to allow the action to annotate code in the PR.
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - name: Load Version
        id: load-version
        run: |
          echo "GOLANGCI_VERSION=v$(cat .golangci-version)"
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: ${{ steps.load-version.outputs.GOLANGCI_VERSION }}
          args: -v -c .golangci.yml
  golang-sec:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - name: Run Gosec Security Scanner
        uses: cosmos/gosec@master
        with:
          args: ./...
