name: Lint Checks
on:
  workflow_call:
# run per commit ci checks against this commit
jobs:
  proto-lint:
    uses: ./.github/workflows/proto.yml
  golangci-lint:
    runs-on: ubuntu-latest
    permissions:
      checks: write # allow write access to checks to allow the action to annotate code in the PR.
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
      - name: Load Version
        id: load-version
        run: |
          GOLANGCI_VERSION=$(cat .golangci-version)
          REV=$(git merge-base origin/master HEAD)
          echo "GOLANGCI_VERSION=$GOLANGCI_VERSION" >> $GITHUB_ENV
          echo "REV=$REV" >> $GITHUB_ENV
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: ${{ env.GOLANGCI_VERSION }}
          args: -v -c .golangci.yml --new-from-rev ${{ env.REV }}
  e2e-evm-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current commit
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Setup nodejs
        uses: actions/setup-node@v3
        with:
          cache: npm
          node-version-file: .tool-versions
          cache-dependency-path: tests/e2e-evm/package-lock.json
      - name: Install npm dependencies
        run: npm install
        working-directory: tests/e2e-evm
      - name: Run solhint
        run: npm run solhint
        working-directory: tests/e2e-evm
      - name: Compile contracts and create artifcats
        run: npm run compile
        working-directory: tests/e2e-evm
      - name: Run linter
        run: npm run lint
        working-directory: tests/e2e-evm
      - name: Run formatter
        run: npm run prettier
        working-directory: tests/e2e-evm
