name: Continuous Integration (Rocksdb Build)

env:
  ROCKSDB_VERSION: v8.10.0

on:
  workflow_call:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo from current commit
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
      - name: build rocksdb dependency
        run: bash ${GITHUB_WORKSPACE}/.github/scripts/install-rocksdb.sh
      - name: build application
        run: make build COSMOS_BUILD_OPTIONS=rocksdb
